# Cross-validation against pymdp on a random POMDP scenario.
#
# Source of truth: `reference/pymdp/random_pomdp_fixtures.json`,
# generated by `reference/pymdp/generate_random_pomdp_fixtures.py`.
#
# Why a random POMDP in addition to T-maze: the T-maze likelihood is
# structured (deterministic at C, perfect at arms, near-deterministic at
# Q). A dense random A/B exercises the full tensor without those
# regularities, surfacing bugs that structure can hide.

using JSON3
using Distributions: Categorical, probs

const RANDOM_FIXTURE_PATH = joinpath(@__DIR__, "..", "..", "reference", "pymdp",
                                      "random_pomdp_fixtures.json")

if !isfile(RANDOM_FIXTURE_PATH)
    @info "pymdp random-POMDP cross-validation skipped: fixtures not generated. " *
          "Run `cd reference/pymdp && uv run python generate_random_pomdp_fixtures.py`."
    return
end

const RANDOM_FIXTURES = JSON3.read(read(RANDOM_FIXTURE_PATH, String))

@testset "random POMDP: matrix encoding agrees with pymdp" begin
    A_pymdp = Matrix{Float64}(undef, length(RANDOM_FIXTURES.A), length(RANDOM_FIXTURES.A[1]))
    for o in eachindex(RANDOM_FIXTURES.A), s in eachindex(RANDOM_FIXTURES.A[o])
        A_pymdp[o, s] = RANDOM_FIXTURES.A[o][s]
    end
    B_pymdp = Array{Float64,3}(undef, length(RANDOM_FIXTURES.B), length(RANDOM_FIXTURES.B[1]),
                                  length(RANDOM_FIXTURES.B[1][1]))
    for sn in eachindex(RANDOM_FIXTURES.B), s in eachindex(RANDOM_FIXTURES.B[sn])
        for a in eachindex(RANDOM_FIXTURES.B[sn][s])
            B_pymdp[sn, s, a] = RANDOM_FIXTURES.B[sn][s][a]
        end
    end
    C_pymdp = Float64.(RANDOM_FIXTURES.C)
    D_pymdp = Float64.(RANDOM_FIXTURES.D)

    # Sanity: A and B columns should be stochastic (valid pymdp output)
    for s in axes(A_pymdp, 2)
        @test sum(A_pymdp[:, s]) ≈ 1 atol=1e-12
    end
    for a in axes(B_pymdp, 3), s in axes(B_pymdp, 2)
        @test sum(B_pymdp[:, s, a]) ≈ 1 atol=1e-12
    end
    @test sum(D_pymdp) ≈ 1 atol=1e-12
end

@testset "random POMDP: per-step posterior matches pymdp" begin
    # Reconstruct A, B, C, D matrices from JSON
    A_pymdp = Matrix{Float64}(undef, length(RANDOM_FIXTURES.A), length(RANDOM_FIXTURES.A[1]))
    for o in eachindex(RANDOM_FIXTURES.A), s in eachindex(RANDOM_FIXTURES.A[o])
        A_pymdp[o, s] = RANDOM_FIXTURES.A[o][s]
    end
    B_pymdp = Array{Float64,3}(undef, length(RANDOM_FIXTURES.B), length(RANDOM_FIXTURES.B[1]),
                                  length(RANDOM_FIXTURES.B[1][1]))
    for sn in eachindex(RANDOM_FIXTURES.B), s in eachindex(RANDOM_FIXTURES.B[sn])
        for a in eachindex(RANDOM_FIXTURES.B[sn][s])
            B_pymdp[sn, s, a] = RANDOM_FIXTURES.B[sn][s][a]
        end
    end
    C_pymdp = Float64.(RANDOM_FIXTURES.C)
    D_pymdp = Float64.(RANDOM_FIXTURES.D)

    m = DiscretePOMDP(A_pymdp, B_pymdp, C_pymdp, D_pymdp)
    agent = Agent(m,
                  FixedPointIteration(num_iter=20, dF_tol=1e-12),
                  EnumerativeEFE(γ=8.0, horizon=2),
                  Deterministic())

    # pymdp 0-indexed obs → Julia 1-indexed
    julia_observations = [Int(o) + 1 for o in RANDOM_FIXTURES.observations]

    for (t, obs) in enumerate(julia_observations)
        a = step!(agent, obs)
        qs = current_belief(agent.history)

        pymdp_posterior = Float64.(RANDOM_FIXTURES.posteriors[t])
        @test probs(qs) ≈ pymdp_posterior atol=1e-6

        # Action equality: same EFE-tie tolerance as in T-maze test
        chosen_step = agent.history.steps[end]
        G_julia_chosen = chosen_step.expected_free_energies[
            findfirst(π -> first(π) == a, chosen_step.policies)]
        pymdp_action_julia = Int(RANDOM_FIXTURES.actions[t]) + 1
        idx_pymdp = findfirst(π -> first(π) == pymdp_action_julia,
                                chosen_step.policies)
        if idx_pymdp !== nothing
            G_pymdp_chosen = chosen_step.expected_free_energies[idx_pymdp]
            @test G_julia_chosen ≈ G_pymdp_chosen atol=1e-6
        end
    end
end
