# Cross-validation against pymdp (Python reference implementation).
#
# Source of truth: `reference/pymdp/tmaze_fixtures.json`, generated by
# `reference/pymdp/generate_tmaze_fixtures.py` using `pymdp.legacy.Agent`
# on the canonical 8-state T-maze.
#
# Verifies that Aifc's outputs (A/B/C/D matrices, per-step
# posteriors, action choices) agree with pymdp on the same model and
# observation sequence — within tolerance suitable for catching real
# numerical divergences (atol=1e-6 on probabilities).
#
# To regenerate the fixtures after a pymdp upgrade or model change:
#   cd reference/pymdp
#   uv run python generate_tmaze_fixtures.py

using JSON3
using Distributions: Categorical, probs

const FIXTURE_PATH = joinpath(@__DIR__, "..", "..", "reference", "pymdp",
                                "tmaze_fixtures.json")

if !isfile(FIXTURE_PATH)
    @info "pymdp cross-validation skipped: fixtures not generated. " *
          "Run `cd reference/pymdp && uv run python generate_tmaze_fixtures.py`."
    return
end

const FIXTURES = JSON3.read(read(FIXTURE_PATH, String))

@testset "matrix encodings agree with pymdp" begin
    m = tmaze_model(cue_reliability=Float64(FIXTURES.cue_reliability),
                     preference=Float64(FIXTURES.preference))

    A_pymdp = reduce(hcat, FIXTURES.A)' |> Matrix |> permutedims |> collect
    # JSON3 reads the 2D arrays as Vector{Vector}; reshape to a Matrix
    A_pymdp = Matrix{Float64}(reduce(hcat, [collect(row) for row in FIXTURES.A]))
    # JSON layout: A[m] is a list of NUM_OBS rows of length NUM_STATES
    # → after `reduce(hcat, rows)`, each column is one row.
    # Easier: build a 2D array directly:
    A_pymdp = Matrix{Float64}(undef, length(FIXTURES.A), length(FIXTURES.A[1]))
    for o in eachindex(FIXTURES.A), s in eachindex(FIXTURES.A[o])
        A_pymdp[o, s] = FIXTURES.A[o][s]
    end
    @test m.A ≈ A_pymdp atol=1e-12

    # B is shape (num_states, num_states, num_actions). JSON-ed as nested lists.
    B_pymdp = Array{Float64,3}(undef, length(FIXTURES.B), length(FIXTURES.B[1]),
                                  length(FIXTURES.B[1][1]))
    for sn in eachindex(FIXTURES.B), s in eachindex(FIXTURES.B[sn])
        for a in eachindex(FIXTURES.B[sn][s])
            B_pymdp[sn, s, a] = FIXTURES.B[sn][s][a]
        end
    end
    @test m.B ≈ B_pymdp atol=1e-12

    @test m.C ≈ Float64.(FIXTURES.C) atol=1e-12
    @test m.D ≈ Float64.(FIXTURES.D) atol=1e-12
end

@testset "per-step posterior matches pymdp on observation sequence" begin
    # pymdp uses enumerative planning by default at policy_len=2 with γ=α=8;
    # we match that configuration exactly. Action selection: deterministic.
    m = tmaze_model(cue_reliability=Float64(FIXTURES.cue_reliability),
                     preference=Float64(FIXTURES.preference))

    agent = Agent(m,
                  FixedPointIteration(num_iter=20, dF_tol=1e-12),
                  EnumerativeEFE(γ=8.0, horizon=2),
                  Deterministic())

    # pymdp's observation indices are 0-based; ours are 1-based.
    pymdp_observations = [Int(o) for o in FIXTURES.observations]
    julia_observations = pymdp_observations .+ 1

    for (t, obs) in enumerate(julia_observations)
        a = step!(agent, obs)
        qs = current_belief(agent.history)

        pymdp_posterior = Float64.(FIXTURES.posteriors[t])
        @test probs(qs) ≈ pymdp_posterior atol=1e-6

        # Action equality is tiebreak-dependent when multiple policies have
        # the same EFE (e.g. all 4 first actions tie when the observation
        # is information-theoretically uninformative given the prior). The
        # robust check is: the agent's chosen action has EFE within ε of
        # pymdp's chosen action.
        chosen_step = agent.history.steps[end]
        G_julia_chosen = chosen_step.expected_free_energies[
            findfirst(π -> first(π) == a, chosen_step.policies)]
        pymdp_action_julia = Int(FIXTURES.actions[t]) + 1
        idx_pymdp = findfirst(π -> first(π) == pymdp_action_julia,
                                chosen_step.policies)
        if idx_pymdp !== nothing
            G_pymdp_chosen = chosen_step.expected_free_energies[idx_pymdp]
            @test G_julia_chosen ≈ G_pymdp_chosen atol=1e-6
        end
    end
end
