# `InductiveEFE` — wrap any base planner with a goal-state-prior weighting.
#
# Friston, Da Costa, Sajid, Heins, Ueltzhöffer, Pavliotis, Parr (2023):
# the agent's planning horizon is augmented with a binary indicator `Z ∈ {0,1}`
# representing whether the goal has been reached. Conditioned on `Z=1`,
# the policy posterior becomes
#
#     q(π | Z=1)  ∝  exp(-γ G(π))  ·  P(Z=1 | π)
#
# where `P(Z=1 | π)` is the *reachability* probability — the chance the
# trajectory generated by `π` visits the goal at any time.
#
# For deterministic dynamics each policy generates a single trajectory, and
# `P(Z=1 | π)` is exactly the indicator of whether that trajectory passes
# through the goal. For stochastic dynamics we use the standard non-Markov
# approximation:
#
#     visited_t  =  visited_{t-1}  +  (1 - visited_{t-1}) · q(s_t = goal | π)
#
# (i.e. treating successive arrivals as independent — exact for
# deterministic dynamics, an approximation otherwise).
#
# To preserve the conformance-test decomposition `G = -(pragmatic + epistemic)`,
# we roll the `log P(Z=1 | π)` term into `pragmatic_value` (it has the
# semantics of a *preference* — over goal-reaching trajectories).

using Distributions: Categorical, probs
using LinearAlgebra: dot

"""
    InductiveEFE(base::PolicyInference; goal_weight=1.0)

Wrap any base policy-inference algorithm so that policies are reweighted by
their probability of reaching the model's `goal_state_prior`. If the model
returns `nothing` from `goal_state_prior`, behaves identically to `base`.

`goal_weight` is the relative weight of the inductive (reachability) prior
versus the base EFE: `combined_neg_G = -G_base + goal_weight · log P(Z=1 | π)`.
With `goal_weight=0` this reduces to `base`.
"""
struct InductiveEFE{P<:PolicyInference, T<:Real} <: PolicyInference
    base::P
    goal_weight::T
end

InductiveEFE(base::PolicyInference; goal_weight::Real = 1.0) =
    InductiveEFE(base, float(goal_weight))

# Forward planner-precision γ via the base.
_planner_gamma(planner::InductiveEFE) = _planner_gamma(planner.base)
_planner_gamma(planner::EnumerativeEFE) = planner.γ
_planner_gamma(planner::SophisticatedInference) = planner.γ

function pragmatic_value(planner::InductiveEFE,
                          m::DiscretePOMDP,
                          qs::Categorical,
                          π::AbstractVector{<:Integer})
    base_prag = pragmatic_value(planner.base, m, qs, π)
    goal_prior = goal_state_prior(m)
    if goal_prior === nothing
        return base_prag
    end
    log_reach = _log_reachability(m, qs, π, goal_prior)
    return base_prag + planner.goal_weight * log_reach
end

function epistemic_value(planner::InductiveEFE,
                          m::DiscretePOMDP,
                          qs::Categorical,
                          π::AbstractVector{<:Integer})
    return epistemic_value(planner.base, m, qs, π)
end

function expected_free_energy(planner::InductiveEFE,
                                m::DiscretePOMDP,
                                qs::Categorical,
                                π::AbstractVector{<:Integer})
    return -(pragmatic_value(planner, m, qs, π) + epistemic_value(planner, m, qs, π))
end

function posterior_policies(planner::InductiveEFE,
                              m::DiscretePOMDP,
                              qs::Categorical,
                              policies::AbstractVector)
    G = [expected_free_energy(planner, m, qs, π) for π in policies]
    q_pi = softmax(.-G, _planner_gamma(planner))
    return q_pi, G
end

function enumerate_policies(planner::InductiveEFE,
                              m::DiscretePOMDP,
                              qs::Categorical)
    return enumerate_policies(planner.base, m, qs)
end

# Forward-simulate q(s_τ | π) and accumulate the probability of having
# visited the goal by step τ. For deterministic dynamics this is exact;
# for stochastic, an approximation that treats arrivals as independent
# across steps. Returns log of that probability (capped at -log(1e12) to
# avoid -Inf sneaking into the policy posterior).
function _log_reachability(m::DiscretePOMDP,
                            qs::Categorical,
                            π::AbstractVector{<:Integer},
                            goal_prior::Categorical)
    cur = collect(probs(qs))
    p_goal = probs(goal_prior)
    visited = dot(cur, p_goal)        # initial mass on goal
    @inbounds for a in π
        cur = m.B[:, :, a] * cur
        p_at_goal = dot(cur, p_goal)
        visited = visited + (1 - visited) * p_at_goal
    end
    return log(max(visited, 1e-12))
end
